FROM arm64v8/ubuntu
COPY qemu-aarch64-static /usr/bin/qemu-aarch64-static
RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install build-essential cmake ninja-build git -y
ENV generator=Ninja
RUN git clone --branch=v2.7.6 --depth=1 --recursive https://github.com/luvit/luvi.git
WORKDIR /luvi
RUN make tiny
RUN make
RUN make test
