
FIND_PATH(PCRE_INCLUDE_DIR NAMES pcre.h)

# Look for the library.
FIND_LIBRARY(PCRE_LIBRARY NAMES pcre)

# Handle the QUIETLY and REQUIRED arguments and set PCRE_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PCRE DEFAULT_MSG PCRE_LIBRARY PCRE_INCLUDE_DIR)

# Copy the results to the output variables.
IF(PCRE_FOUND)
  SET(PCRE_LIBRARIES ${PCRE_LIBRARY})
  SET(PCRE_INCLUDE_DIRS ${PCRE_INCLUDE_DIR})
  SET(PCRE_UNIT_WIDTH ${PCRE_CODE_UNIT_WIDTH})
ELSE(PCRE_FOUND)
  SET(PCRE_LIBRARIES)
  SET(PCRE_INCLUDE_DIRS)
  SET(PCRE_UNIT_WIDTH)
ENDIF(PCRE_FOUND)

ADD_DEFINITIONS( -DPCRE_CODE_UNIT_WIDTH=${PCRE_UNIT_WIDTH} )

MARK_AS_ADVANCED(PCRE_INCLUDE_DIRS PCRE_LIBRARIES PCRE_UNIT_WIDTH)
