
FIND_PATH(PCRE2_INCLUDE_DIR NAMES pcre2.h)

# Look for the library.
FIND_LIBRARY(PCRE2_LIBRARY NAMES pcre2)

# Handle the QUIETLY and REQUIRED arguments and set PCRE2_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PCRE2 DEFAULT_MSG PCRE2_LIBRARY PCRE2_INCLUDE_DIR)

# Copy the results to the output variables.
IF(PCRE2_FOUND)
  SET(PCRE2_LIBRARIES ${PCRE2_LIBRARY})
  SET(PCRE2_INCLUDE_DIRS ${PCRE2_INCLUDE_DIR})
  SET(PCRE2_UNIT_WIDTH ${PCRE2_CODE_UNIT_WIDTH})
ELSE(PCRE2_FOUND)
  SET(PCRE2_LIBRARIES)
  SET(PCRE2_INCLUDE_DIRS)
  SET(PCRE2_UNIT_WIDTH)
ENDIF(PCRE2_FOUND)

ADD_DEFINITIONS( -DPCRE2_CODE_UNIT_WIDTH=${PCRE2_UNIT_WIDTH} )

MARK_AS_ADVANCED(PCRE2_INCLUDE_DIRS PCRE2_LIBRARIES PCRE2_UNIT_WIDTH)
